sudo: false
language: python
python:
  - "3.6"
install:
  # Install python
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install virtual enviroment 
  - conda create -q -n quantumpropagator python=3.6
  - conda install --name quantumpropagator -c anaconda hdf5
  - source activate quantumpropagator

  # Package dependencies
  - pip install --upgrade pip
  - pip install nose coverage cython numpy
  - source activate quantumpropagator

  # Install quantumpropagator package
  - python -c 'import numpy as np; np.get_include()'  
  - python -c 'import numpy.core; print(numpy.core.__file__)'
  - python setup.py develop
  
script:
  # Run the unitary tests excluding the expensive computations
  - nosetests --with-coverage --cover-erase --cover-package=quantumpropagator -v

branches:
  only:
   - master

